backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "galeria"
    label: "Galeria"
    folder: "content/galeria"
    create: true
    slug: "{{slug}}"
    format: "json"
    fields:
      - { label: "Título", name: "title", widget: "string" }

      - { label: "Localização", name: "location", widget: "string", required: false }

      - { label: "Capa", name: "cover", widget: "image" }

      - label: "Imagens"
        name: "images"
        widget: "list"
        field: { label: "Imagem", name: "image", widget: "image" }